version: "3"

services:
  tile38-leader:
    build:
      context: ./tile38
    container_name: tile38-leader
    ports:
      - 9851:9851
    command: [ "tile38-server", "-vv" ]
    hostname: tile38

  filler:
    build:
      context: ./filler
    depends_on:
      - tile38-leader
    volumes:
      - ./data:/data
