version: "3"

services:
  tile38-leader:
    build:
      context: ./tile38
    container_name: tile38-leader
    ports:
      - 9851:9851
    command: [ "tile38-server", "-vv" ]

  # filler:
  #   build:
  #     context: ./filler
  #   depends_on:
  #     - tile38-leader
  #   volumes:
  #     - ./data:/data

  filler-debug:
    build:
      context: ./filler
    depends_on:
      - tile38-leader
    volumes:
      - ./data:/data
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: [ "/bin/bash" ]
